import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';

export default [
  {
    files: ['**/*.{js,mjs,cjs,ts}']
  },
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node
      }
    }
  },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    rules: {
      'array-callback-return': 'warn',
      'accessor-pairs': 'off',
      'arrow-body-style': 'off',
      'block-scoped-var': 'error',
      'camelcase': 'error',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      'complexity': 'error',
      'consistent-return': 'error',
      'consistent-this': 'warn',
      'curly': 'error',
      'default-case': 'error',
      'default-case-last': 'warn',
      'default-param-last': 'warn',
      'dot-notation': 'warn',
      'eqeqeq': 'error',
      'func-name-matching': 'warn',
      'func-names': 'warn',
      'func-style': 'off',
      'grouped-accessor-pairs': 'warn',
      'guard-for-in': 'warn',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'init-declarations': 'off',
      'max-lines': 'warn',
      'max-classes-per-file': 'off',
      'max-depth': 'error',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'error',
      'max-params': 'warn',
      'max-statements': 'off',
      'logical-assignment-operators': 'warn',
      'new-cap': ['error', {
        newIsCap: true,
        capIsNew: false,
        capIsNewExceptions: ['Component', 'Directive', 'Injectable', 'NgModule']
      }],
      'no-alert': 'warn',
      'no-array-constructor': 'off',
      'no-await-in-loop': 'error',
      'no-bitwise': 'off',
      'no-caller': 'off',
      'no-case-declarations': 'warn',
      'no-console': 'warn',
      'no-constructor-return': 'error',
      'no-continue': 'warn',
      'no-delete-var': 'warn',
      'no-div-regex': 'off',
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-empty': 'error',
      'no-empty-function': 'error',
      'no-empty-static-block': 'error',
      'no-eq-null': 'error',
      'no-eval': 'warn',
      'no-inner-declarations': 'error',
      'no-promise-executor-return': 'warn',
      'no-self-compare': 'error',
      'no-unreachable-loop': 'error',
      'no-use-before-define': 'error',
      'no-useless-assignment': 'warn',
      'require-atomic-updates': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'warn',
      'no-extra-label': 'warn',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'warn',
      'no-inline-comments': 'off',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'off',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'warn',
      'no-loop-func': 'error',
      'no-magic-numbers': 'warn',
      'no-multi-assign': 'error',
      'no-multi-str': 'off',
      'no-negated-condition': 'off',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-octal-escape': 'warn',
      'no-param-reassign': 'error',
      'no-plusplus': 'off',
      'no-proto': 'warn',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'warn',
      'no-restricted-properties': 'warn',
      'no-restricted-syntax': 'off',
      'no-return-assign': 'error',
      'no-script-url': 'warn',
      'no-sequences': 'error',
      'no-shadow': 'error',
      'no-ternary': 'off',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-underscore-dangle': 'warn',
      'no-unneeded-ternary': 'error',
      'no-unused-expressions': 'error',
      'no-useless-call': 'warn',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'no-warning-comments': 'warn',
      'object-shorthand': 'warn',
      'one-var': 'off',
      'operator-assignment': ['warn', 'always'],
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'error',
      'prefer-destructuring': ['error', {
        'array': true,
        'object': true
      }],
      'prefer-named-capture-group': 'warn',
      'prefer-numeric-literals': 'off',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'error',
      'prefer-template': 'warn',
      'radix': 'off',
      'require-unicode-regexp': 'warn',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'strict': 'off',
      'symbol-description': 'off',
      'vars-on-top': 'warn',
      'yoda': 'warn'
    }
  }
];
