# Generated by Django 4.2.11 on 2026-02-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("from_email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Billing", "Billing"),
                            ("Bug", "Bug"),
                            ("Feature", "Feature"),
                            ("Account", "Account"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Low",
                        max_length=10,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("suggested_reply", models.TextField(blank=True)),
                ("feedback_accepted", models.BooleanField(blank=True, null=True)),
                ("feedback_comment", models.TextField(blank=True, default="")),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
